'use strict';
// ─────────────────────────────────────────────────────────────────────────────
//  sources/pushReceiver.js - HTTPS/HTTP receiver for CVAccess "CVConnect"
//  cloud/event push (the integration discovered on the gym PC).
//
//  CVAccess Cloud Settings lets you point "push event data to the cloud
//  platform" at an HTTP(S) URL. Default 127.0.0.1:6001 is owned by the ZKTeco
//  CVConnect client on many installs, so the connector defaults to a free port
//  (8091) and the CVAccess Cloud Settings URL must match it.
//
//  Two transport modes (config sources.cvaccessPush.scheme):
//    * "https"  - serves TLS. CVAccess's client must trust our certificate:
//                 import cert.pem (generated by tools/cert-tool.js) into the
//                 Windows "Trusted Root Certification Authorities".
//    * "http"   - no TLS. If the CVAccess Cloud Settings URL field accepts
//                 http://, use this to skip certificate trust (loopback on an
//                 access-controlled LAN is acceptable).
//
//  This receiver NEVER uses port 8088 (CVAccess owns it). Default 8091.
//  When captureFirst=true, the first POST body is logged verbatim so the real
//  CVAccess event shape can be mapped into config/config.json.
// ─────────────────────────────────────────────────────────────────────────────

const http = require('http');
const https = require('https');
const fs = require('fs');
const path = require('path');
const { normalizeEvent } = require('../normalizer');
const { TransientError } = require('../errors');

function ParseBody(contentType, buf) {
  const text = buf.toString('utf8');
  if (!text) return {};
  if ((contentType || '').includes('application/json') || text.trimStart().startsWith('{')) {
    try { return JSON.parse(text); } catch (_) { return { raw: text }; }
  }
  const out = {};
  for (const pair of text.split('&')) {
    const i = pair.indexOf('=');
    if (i < 0) continue;
    try {
      out[decodeURIComponent(pair.slice(0, i))] = decodeURIComponent(pair.slice(i + 1));
    } catch (_) { /* keep */ }
  }
  return out;
}

class PushReceiver {
  constructor({ cfg, sourceCfg, connectorId, log, home }) {
    this.cfg = cfg;
    this.sourceCfg = sourceCfg || {};
    this.connectorId = connectorId;
    this.log = log || console;
    this.home = home || process.env.GDC_HOME || __dirname;
    this.host = this.sourceCfg.listenHost || '0.0.0.0';
    this.port = this.sourceCfg.listenPort || 8091;
    this.scheme = (this.sourceCfg.scheme || 'https').toLowerCase();
    this.maxBodyBytes = this.sourceCfg.maxBodyBytes || 131072;
    this.captureFirst = !!this.sourceCfg.captureFirst;
    this.server = null;
    this.onEvent = null;
    this.stat = { received: 0, accepted: 0, filtered: 0, captured: 0 };
    this._cert = this.sourceCfg.certFile || path.join(this.home, 'config', 'cert.pem');
    this._key = this.sourceCfg.keyFile || path.join(this.home, 'config', 'key.pem');
  }

  _tlsOptions() {
    if (this.scheme !== 'https') return null;
    if (!fs.existsSync(this._cert) || !fs.existsSync(this._key)) {
      throw new TransientError(
        'HTTPS push receiver needs config/cert.pem + config/key.pem ' +
        '(run: node tools/cert-tool.js) or switch cvaccessPush.scheme to "http".'
      );
    }
    return {
      cert: fs.readFileSync(this._cert),
      key: fs.readFileSync(this._key),
    };
  }

  async start(onEvent) {
    this.onEvent = onEvent;
    const mod = this.scheme === 'https' ? https : http;
    const opts = this.scheme === 'https' ? this._tlsOptions() : null;
    this.server = opts
      ? https.createServer(opts, (req, res) => this._handle(req, res))
      : http.createServer((req, res) => this._handle(req, res));

    await new Promise((resolve, reject) => {
      this.server.once('error', (err) => {
        if (err && (err.code === 'EACCES' || err.code === 'EADDRINUSE')) {
          reject(new Error(
            `Cannot listen on ${this.host}:${this.port} (${err.code}). ` +
            `Port in use or excluded. Check: netstat -ano | findstr :${this.port}, ` +
            'and Windows excluded ranges (netsh interface ipv4 show excludedportrange protocol=tcp). ' +
            'If another app (e.g. ZKTeco CVConnect client) owns 6001, choose a free port and set ' +
            'cvaccessPush.listenPort + the CVAccess Cloud Settings URL to it. ' +
            '8041/8091/8093 are usually free.'
          ));
        } else {
          reject(err);
        }
      });
      this.server.listen(this.port, this.host, () => {
        this.log.info('cvaccess.push.listening', {
          scheme: this.scheme, host: this.host, port: this.port,
        });
        resolve();
      });
    });
    return this;
  }

  stop() {
    if (this.server) {
      try { this.server.close(); } catch (_) {}
      this.server = null;
    }
  }

  _handle(req, res) {
    if (req.method !== 'POST' && req.method !== 'PUT') {
      res.writeHead(405, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ error: 'method not allowed' }));
      return;
    }
    const chunks = [];
    let received = 0;
    let overflow = false;
    req.on('data', (c) => {
      received += c.length;
      if (received > this.maxBodyBytes) {
        overflow = true;
        req.destroy();
        return;
      }
      chunks.push(c);
    });
    req.on('end', async () => {
      if (overflow) {
        res.writeHead(413, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ accepted: false, reason: 'body too large' }));
        return;
      }
      const buf = Buffer.concat(chunks);
      const raw = buf.toString('utf8');
      this.stat.received += 1;

      // Log EVERY packet at INFO level (default) so nothing is invisible.
      this.log.info('cvaccess.push.packet', {
        receivedTotal: this.stat.received,
        contentType: req.headers['content-type'] || '',
        body: raw.slice(0, 8000),
      });

      // capture-first: dump the real event shape once for field mapping
      if (this.captureFirst && !this.stat.captured) {
        this.stat.captured = 1;
        this.log.warn('cvaccess.push.capture', {
          hint: 'first real packet captured - map fields in config/config.json',
          contentType: req.headers['content-type'] || '',
          body: raw.slice(0, 4000),
        });
      }

      const parsed = ParseBody(req.headers['content-type'] || '', buf);
      this.log.debug('cvaccess.push.envelope', {
        sid: parsed?.sid ?? undefined,
        payloadKeys: parsed?.payload ? Object.keys(parsed.payload) : undefined,
        hasTransactions: Array.isArray(parsed?.payload?.transactions),
        topLevelArray: Array.isArray(parsed),
        nTransactions: Array.isArray(parsed?.payload?.transactions) ? parsed.payload.transactions.length : 0,
      });

      // CVAccess cloud push envelope: { payload: { transactions: [...] }, sid }
      let records;
      if (parsed && Array.isArray(parsed.payload?.transactions)) {
        records = parsed.payload.transactions;
      } else {
        records = Array.isArray(parsed) ? parsed : [parsed];
      }
      const summary = { records: records.length, accepted: 0, filtered: 0 };
      for (const item of records) {
        if (!item || typeof item !== 'object') continue;
        // Log a SANITIZED shape of every record (never biometrics/templates).
        this.log.debug('cvaccess.push.record', {
          id: item.id !== undefined ? item.id : undefined,
          reId: item.reId !== undefined ? item.reId : undefined,
          deviceSn: item.deviceSn !== undefined ? item.deviceSn : undefined,
          deviceName: item.deviceName !== undefined ? item.deviceName : undefined,
          eventName: item.eventName !== undefined ? item.eventName : undefined,
          eventNameKey: item.eventNameKey !== undefined ? item.eventNameKey : undefined,
          verifyType: item.verifyType !== undefined ? item.verifyType : undefined,
          eventTime: item.eventTime !== undefined ? item.eventTime : undefined,
          eventTypeCode: item.eventTypeCode !== undefined ? item.eventTypeCode : undefined,
        });
        const out = normalizeEvent(
          item, this.cfg,
          { mapping: this.sourceCfg.mapping },
          { connectorId: this.connectorId }
        );
        if (out.filtered) {
          summary.filtered += 1;
          this.stat.filtered += 1;
          // Print filtered events at WARN so they are impossible to miss.
          this.log.warn('cvaccess.push.filtered', {
            reason: out.reason,
            record: {
              id: item.id !== undefined ? item.id : undefined,
              reId: item.reId !== undefined ? item.reId : undefined,
              deviceSn: item.deviceSn !== undefined ? item.deviceSn : undefined,
              eventName: item.eventName !== undefined ? item.eventName : undefined,
              verifyType: item.verifyType !== undefined ? item.verifyType : undefined,
              eventTime: item.eventTime !== undefined ? item.eventTime : undefined,
            },
          });
          continue;
        }
        summary.accepted += 1;
        this.stat.accepted += 1;
        this.log.info('cvaccess.push.event', {
          deviceId: out.normalized.deviceId,
          userId: out.normalized.userId,
          method: out.normalized.method,
          timestamp: out.normalized.timestamp,
          eventType: out.normalized.eventType,
          eventId: out.normalized.eventId,
        });
        if (this.onEvent) {
          await this.onEvent({ source: 'cvaccess-push', record: item, normalized: out.normalized });
        }
      }
      this.log.info('cvaccess.push.summary', {
        sid: parsed?.sid ?? undefined,
        total: summary.records,
        accepted: summary.accepted,
        filtered: summary.filtered,
        receivedTotal: this.stat.received,
      });
      res.writeHead(202, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ accepted: true, received: this.stat.received, acceptedEvents: this.stat.accepted }));
    });
  }
}

module.exports = { PushReceiver };